repos:
  - repo: https://github.com/psf/black
    rev: 23.3.0  # Use uma versão estável do Black
    hooks:
      - id: black
        language_version: python3.12

  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1  # Use a versão do isort que desejar
    hooks:
      - id: isort
        name: isort (imports formatting)
        args: ["--profile", "black"]

  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
