version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - FIXED_TOKEN=${FIXED_TOKEN}
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: zuplae
      POSTGRES_PASSWORD: platform2024
      POSTGRES_DB: zpe_platform_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
