version: '3.8'

services:
  zpe_backend:
    build: .
    image: zuplae/zuplae-platform-backend
    container_name: zpe-platform-backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      # Sobrescreva a URL de conexão do banco de dados para se conectar ao serviço 'db'
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    env_file:
      - .env  # Use o arquivo .env global
    volumes:
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000

  db:
    image: postgres:14
    container_name: zpe-platform-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}  # Pegue do arquivo .env
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}  # Pegue do arquivo .env
      POSTGRES_DB: ${POSTGRES_DB}  # Pegue do arquivo .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
