version: '3.8'

services:
  zpe_backend:
    image: zuplae/zuplae-platform-backend
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - POSTGRES_DB=zpe_platform_db
      - POSTGRES_USER=zpe
      - POSTGRES_PASSWORD=platforma@1508
      - DATABASE_URL=postgresql://zpe:platforma@1508@db:5432/zpe_platform_db

  db:
    image: postgres:14
    environment:
      POSTGRES_DB: zpe_platform_db
      POSTGRES_USER: zpe
      POSTGRES_PASSWORD: platforma@1508
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
